apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
    app: {{ .Values.service.name }}
    tier: frontend
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: 8069
    protocol: TCP
    name: {{ .Values.service.name }}
  selector:
    app: {{ .Release.Name }}
    tier: frontend
