apiVersion: v1
kind: Service
metadata:
  name: svc-{{ .Release.Name }}
  labels:
    app: svc-{{ .Release.Name }}
    tier: frontend
spec:
  type: NodePort
  ports:
  - port: 8069
    protocol: TCP
    name: svc-{{ .Release.Name }}
  selector:
    app: {{ .Release.Name }}
    tier: frontend
