apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-odoo-admin-pass"
  labels:
    app: {{ .Release.Name }}
type: Opaque
data:
  password:  {{ .Values.odoo.admin_password | b64enc | quote }}
